### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by nutsofamily** [dennyreiter/NHLStandings-HA#1]
Thanks for this!
So to install would I create a separate folder in www or elsewhere, download the files and then from within node red import?
Sorry.
Noobish.

**Comment by dennyreiter** [comment]
No, the yaml file you would paste into your Lovelace dashboard. The json
file you import into Node-RED.

**Comment by nutsofamily** [comment]
Thanks I figured that out just before u sent that to me LOL.
After pasting it in I get 2 unknown :array loop.
![Screen Shot 2021-03-14 at 11 47 27 AM](https://user-images.githubusercontent.com/24458433/111080603-72d1c400-84bc-11eb-956c-60306a68ee4f.png)


Also Could you post  an example lovelace card? 
Im missing something simple to add it to lovelace. I did install llist-card but obviously pasting the yaml code into the card wont work…..


I appreciate the correspondence! 
Thanks.

**Comment by nutsofamily** [comment]
My Dashboard successfully has the new tabs for the node to populate but again I cannot deploy due to the unknon arrays….

**Comment by dennyreiter** [comment]
Let me look, now I wonder if that wasn't a contrib node and didn't realize
it.

**Comment by nutsofamily** [comment]
Thanks. This looks so cool and exactly what I was wanting. Fingers crossed!

**Comment by dennyreiter** [comment]
OK, it looks like in Node-RED you also need to install

https://flows.nodered.org/node/node-red-contrib-loop-processing

I'm going to try and get it to work with the split node again, but it
wasn't cooperating.

**Comment by dennyreiter** [comment]
If you give me just a little bit, I have an updated flow I'm uploading

**Comment by nutsofamily** [comment]
Thats awesome, do I still need to install loop-processing? Is it a custom repo to install via Hacs?

**Comment by dennyreiter** [comment]
OK, it is updated.  the loop processing is in Node-RED, you install it uder the "manage palette' menu option.  The new flow file also downloads the Team info from the API to get the proper locationName, teamName, and also the team URL.  I'd delete out the previous flow and then import this one.

This was really helpful, things I wouldn't have thought to check before releasing it.

**Comment by nutsofamily** [comment]
It doesn't seem to populate the panel with anything. It deployed successfully though.

**Comment by dennyreiter** [comment]
You might have to click on them inject nodes (blue/grey) on the left that
say Get Hockey Teams and Get Hockey Standings the first time.

**Comment by nutsofamily** [comment]
I have the sensor entities and looking at them they seem to have the data but my lovelace isnt showing anything.
I copied theyaml and placed it into my main lovelace dashboard, I have list-card installed via hacs.

**Comment by nutsofamily** [comment]
Ok central, west and north now work, have to figure to get the other ones

**Comment by nutsofamily** [comment]
Yup East and League dont update. I know its my end..

**Comment by dennyreiter** [comment]
The list card is very finicky. I'll look it over on my end again. Glad it's
working this far though!

**Comment by nutsofamily** [comment]
![Screen Shot 2021-03-14 at 6 14 14 PM](https://user-images.githubusercontent.com/24458433/111091735-2ce32300-84f1-11eb-89e2-c48b781d32fc.png)
Shows the standings sensor populates but just doesn't put any info on the lovelace page

**Comment by dennyreiter** [comment]
That is weird. I think what I would do is copy the yaml from the league tab to a text file, then cut everything after say, "add_link: teamLink" and see if it populates, then keep adding columns until it breaks. Sorry, mine is populating just fine.

**Comment by nutsofamily** [comment]
Just for the heck of it can u post the league yaml and east yaml?
It's weird that the entity works but doesn't publish to the list card.

I'll plod along but in either case thanks so much for this awesome edition!!!

**Comment by dennyreiter** [comment]
League:

type: 'custom:list-card'
title: NHL League Standings
entity: sensor.nhl_standings
feed_attribute: rank
columns:
  - title: Rank
    field: leagueRank
  - title: ''
    type: image
    field: logo
    add_link: teamLink
  - title: Team
    field: locationName
    add_link: teamLink
  - title: GP
    field: gamesPlayed
  - title: W
    field: wins
  - title: L
    field: losses
  - title: OT
    field: ot
  - title: PTS
    field: points
  - title: P%
    field: pointsPercentage
  - title: RW
    field: regulationWins
  - title: ROW
    field: row
  - title: GF
    field: goalsScored
  - title: GA
    field: goalsAgainst
  - title: DIFF
    field: diff
  - title: HOME
    field: homeRecord
  - title: AWAY
    field: awayRecord
  - title: S/O
    field: shootOutsRecord
  - title: L10
    field: lastTenRecord
  - title: STRK
    field: streakCode
card_mod:
  style: |
    ha-card {
      font-size: 1.2em;;
    }
    td.leagueRank {
      font-size: 2em;
      padding-left: 10px;
    }


East:

type: 'custom:list-card'
title: NHL Mass Mutual East Standings
entity: sensor.nhl_division_mass_mutual_east
feed_attribute: team_records
columns:
  - title: Rank
    field: divisionRank
  - title: ''
    field: logo
    type: image
  - title: Team
    field: name
    style:
      - border-style: none
  - title: GP
    field: gamesPlayed
  - title: W
    field: wins
  - title: L
    field: losses
  - title: OT
    field: ot
  - title: PTS
    field: points
  - title: P%
    field: pointsPercentage
  - title: RW
    field: regulationWins
  - title: ROW
    field: row
  - title: GF
    field: goalsScored
  - title: GA
    field: goalsAgainst
  - title: DIFF
    field: diff
  - title: HOME
    field: homeRecord
  - title: AWAY
    field: awayRecord
  - title: S/O
    field: shootOutsRecord
  - title: L10
    field: lastTenRecord
  - title: STRK
    field: streakCode


East, Wesr, etc should all be identical, just the entity changing.

**Comment by nutsofamily** [comment]
Sorry yaml code format

**Comment by nutsofamily** [comment]
![Screen Shot 2021-03-14 at 9 28 29 PM](https://user-images.githubusercontent.com/24458433/111103722-56f60e80-850c-11eb-9349-e4774763f533.png)
So frustrating I cannot get this nor the Easy to show.

**Comment by nutsofamily** [comment]
![Screen Shot 2021-03-14 at 9 47 07 PM](https://user-images.githubusercontent.com/24458433/111105010-2e234880-850f-11eb-938c-cc68d21c3d07.png)
Is this the output u get after running the flow?

**Comment by nutsofamily** [comment]
Ok, tried again from scratch. ran the nodes many times. Everything disappeared.  Checked my entities and found orphaned ones. Deleted, renamed the working ones and VOILA. All works.
![Screen Shot 2021-03-14 at 10 00 45 PM](https://user-images.githubusercontent.com/24458433/111105705-c79f2a00-8510-11eb-8c6b-b43f47aa4d30.png)
![Uploading Screen Shot 2021-03-14 at 10.01.21 PM.png…]()

**Comment by dennyreiter** [comment]
Yay!

**Comment by dennyreiter** [comment]
I'm glad it worked finally, sorry for the problems and thanks for being a guinea pig :)  I'm going to add some notes for troubleshooting.

**Comment by nutsofamily** [comment]
Hi This is what I use to call service to make a sound through my alexa device:

`service: media_player.play_media
data:
  media_content_id: amzn_sfx_doorbell_chime_01
  media_content_type: sound
target:
  device_id: 3bf307226e5b95486d5befed8c0113db`

Any idea where i would put this for the horn sounds?
