### ISSUE TITLE
League not updated

### ISSUE THREAD

**Issue by nutsofamily** [dennyreiter/NHLStandings-HA#3]
Hi anything change on this? My league still shows data from a year ago.

**Comment by dennyreiter** [comment]
I probably have to rework it with them switching divisions back around, just haven't had time

**Comment by Gruzzen** [comment]
I updated the Node Red Flow for the current season.

Make sure you also change the names of your sensors within Home Assistant.



`[{"id":"97abbf6f.4e4ca","type":"inject","z":"57910e50.9be5","name":"Get Hockey Standings","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"3600","crontab":"","once":false,"onceDelay":0.1,"topic":"","payloadType":"date","x":430,"y":300,"wires":[["4c1434bb.0b567c"]]},{"id":"86943634.e4d8e8","type":"comment","z":"57910e50.9be5","name":"NHL Standings","info":"","x":348,"y":253,"wires":[]},{"id":"4c1434bb.0b567c","type":"change","z":"57910e50.9be5","name":"Standings API","rules":[{"t":"set","p":"headers['User-Agent']","pt":"msg","to":"Chrome/68.0.3440.106 Safari/537.36","tot":"str"},{"t":"set","p":"url","pt":"msg","to":"https://statsapi.web.nhl.com/api/v1/standings?expand=standings.record","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":666,"y":300,"wires":[["2ac155c1.57a2da"]]},{"id":"2ac155c1.57a2da","type":"http request","z":"57910e50.9be5","name":"GET","method":"GET","ret":"obj","paytoqs":"ignore","url":"","tls":"","persist":false,"proxy":"","authType":"","senderr":false,"x":820,"y":300,"wires":[["1839047e.790a2c"]]},{"id":"cfabf953.2daa98","type":"link out","z":"57910e50.9be5","name":"Divisions Out","links":["4fbc7d56.5d8a04"],"x":1335,"y":340,"wires":[]},{"id":"4fbc7d56.5d8a04","type":"link in","z":"57910e50.9be5","name":"Divisiions In","links":["cfabf953.2daa98"],"x":220,"y":440,"wires":[["19838db6.1a98c2"]]},{"id":"b5f0c46c.181018","type":"ha-entity","z":"57910e50.9be5","name":"League Standings","server":"28e7bd5c.77b7ca","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"nhl_standings"},{"property":"device_class","value":""},{"property":"icon","value":"mdi:hockey-sticks"},{"property":"unit_of_measurement","value":""}],"state":"","stateType":"date","attributes":[{"property":"rank","value":"league","valueType":"flow"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":1490,"y":260,"wires":[[]]},{"id":"930172d3.086c5","type":"array-loop","z":"57910e50.9be5","name":"Iterate Divisions","key":"al61a1ecc6700c15","keyType":"msg","reset":false,"resetValue":"value-null","array":"divisions","arrayType":"flow","x":1280,"y":300,"wires":[["b5f0c46c.181018"],["cfabf953.2daa98"]]},{"id":"1839047e.790a2c","type":"change","z":"57910e50.9be5","name":"Set up flows","rules":[{"t":"set","p":"divisions","pt":"flow","to":"payload.records","tot":"msg"},{"t":"set","p":"league","pt":"flow","to":"[]","tot":"json"}],"action":"","property":"","from":"","to":"","reg":false,"x":1050,"y":300,"wires":[["930172d3.086c5","7a5303581d1d81c0"]]},{"id":"4a490983.982c58","type":"link out","z":"57910e50.9be5","name":"Continue Division Loop Out","links":["8950ebb6.b84dd8"],"x":1260,"y":580,"wires":[]},{"id":"8950ebb6.b84dd8","type":"link in","z":"57910e50.9be5","name":"Continue Division Loop In","links":["4a490983.982c58"],"x":1050,"y":240,"wires":[["930172d3.086c5"]]},{"id":"19838db6.1a98c2","type":"change","z":"57910e50.9be5","name":"Division Info","rules":[{"t":"set","p":"nhl_division_id","pt":"flow","to":"payload.division.id","tot":"msg"},{"t":"set","p":"nhl_division_name","pt":"flow","to":"payload.division.name","tot":"msg"},{"t":"set","p":"nhl_standings_type","pt":"flow","to":"payload.standingsType","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":390,"y":440,"wires":[["9bb0c1d2.f2d92"]]},{"id":"4bd3c5b6.b603ec","type":"switch","z":"57910e50.9be5","name":"","property":"nhl_division_id","propertyType":"flow","rules":[{"t":"eq","v":"18","vt":"num"},{"t":"eq","v":"17","vt":"num"},{"t":"eq","v":"16","vt":"num"},{"t":"eq","v":"15","vt":"num"},{"t":"else"}],"checkall":"true","repair":false,"outputs":5,"x":380,"y":640,"wires":[["fedd6442.b35558"],["80e85d03.9dda1"],["53a8307e.193f9"],["8c2c22bf.4c20c"],["abe22a40.c45d28"]]},{"id":"abe22a40.c45d28","type":"debug","z":"57910e50.9be5","name":"Impossibru Division!","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","statusVal":"$flowContext('nhl_division_id')","statusType":"jsonata","x":720,"y":760,"wires":[]},{"id":"b745aebc.5cab2","type":"array-loop","z":"57910e50.9be5","name":"Iterate Teams","key":"al61a1ecc6700c14","keyType":"msg","reset":true,"resetValue":"value-null","array":"teams","arrayType":"flow","x":1190,"y":620,"wires":[["4a490983.982c58"],["edf62832.a18788"]]},{"id":"1820f809.f6c418","type":"link out","z":"57910e50.9be5","name":"Rankings Out","links":["ec911487.fb99e8"],"x":1520,"y":660,"wires":[]},{"id":"ec911487.fb99e8","type":"link in","z":"57910e50.9be5","name":"Rankings In","links":["1820f809.f6c418"],"x":980,"y":580,"wires":[["b745aebc.5cab2"]]},{"id":"edf62832.a18788","type":"function","z":"57910e50.9be5","name":"Fix up team division info","func":"\nmsg.payload.division_name = flow.get('nhl_division_name');\nmsg.payload.division_id = flow.get('nhl_division_id');\nmsg.payload.standings_type = flow.get('nhl_standings_type');\nlet dict = flow.get('league') || {};\ndict[parseInt(msg.payload.leagueRank)-1] = msg.payload;\nflow.set('league', dict);\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":1450,"y":660,"wires":[["1820f809.f6c418"]]},{"id":"80e85d03.9dda1","type":"ha-entity","z":"57910e50.9be5","name":"Atlantic","server":"28e7bd5c.77b7ca","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"nhl_division_atlantic"},{"property":"device_class","value":""},{"property":"icon","value":"mdi:hockey-sticks"},{"property":"unit_of_measurement","value":""}],"state":"teams[0].name","stateType":"flow","attributes":[{"property":"standings_type","value":"nhl_standings_type","valueType":"flow"},{"property":"team_records","value":"teams","valueType":"flow"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":674,"y":596,"wires":[["b745aebc.5cab2"]]},{"id":"53a8307e.193f9","type":"ha-entity","z":"57910e50.9be5","name":"Central","server":"28e7bd5c.77b7ca","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"nhl_division_central"},{"property":"device_class","value":""},{"property":"icon","value":"mdi:hockey-sticks"},{"property":"unit_of_measurement","value":""}],"state":"teams[0].name","stateType":"flow","attributes":[{"property":"standings_type","value":"nhl_standings_type","valueType":"flow"},{"property":"team_records","value":"teams","valueType":"flow"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":650,"y":643,"wires":[["b745aebc.5cab2"]]},{"id":"8c2c22bf.4c20c","type":"ha-entity","z":"57910e50.9be5","name":"Pacific","server":"28e7bd5c.77b7ca","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"nhl_division_pacific"},{"property":"device_class","value":""},{"property":"icon","value":"mdi:hockey-sticks"},{"property":"unit_of_measurement","value":""}],"state":"teams[0].name","stateType":"flow","attributes":[{"property":"standings_type","value":"nhl_standings_type","valueType":"flow"},{"property":"team_records","value":"teams","valueType":"flow"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":650,"y":700,"wires":[["b745aebc.5cab2"]]},{"id":"fedd6442.b35558","type":"ha-entity","z":"57910e50.9be5","name":"Metropolitan","server":"28e7bd5c.77b7ca","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"nhl_division_metropolitan"},{"property":"device_class","value":""},{"property":"icon","value":"mdi:hockey-sticks"},{"property":"unit_of_measurement","value":""}],"state":"teams[0].name","stateType":"flow","attributes":[{"property":"standings_type","value":"nhl_standings_type","valueType":"flow"},{"property":"team_records","value":"teams","valueType":"flow"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":680,"y":540,"wires":[["b745aebc.5cab2"]]},{"id":"d0cc300.ee6dbd","type":"comment","z":"57910e50.9be5","name":"Fix up the team info for each division","info":"","x":370,"y":380,"wires":[]},{"id":"b9b3b695.0b1fc8","type":"comment","z":"57910e50.9be5","name":"Add teams to League Rankings","info":"After the teams in the Division are fixed up and spit out, iterate over them once again to put them into a League array sorted by their rank, which then gets spit out as a standings sensor.","x":1210,"y":536,"wires":[]},{"id":"cb440b00.2b05b8","type":"function","z":"57910e50.9be5","name":"Fix up team info","func":"function slugify(text)\n{\n  return text.toString().toLowerCase()\n    .replace(/\\s+/g, '_')           // Replace spaces with -\n    .replace(/[^\\w\\-]+/g, '_')       // Remove all non-word chars\n    .replace(/\\-\\-+/g, '-')         // Replace multiple - with single -\n    .replace(/^-+/, '')             // Trim - from start of text\n    .replace(/-+$/, '');            // Trim - from end of text\n}\n\nvar teams_info = flow.get('nhl_teams');\nmsg.payload.team_entity_name = \"nhl_standings_\".concat(slugify(msg.payload.team.name));\nmsg.payload.logo =\"https://www-league.nhlstatic.com/images/logos/teams-current-primary-light/\".concat(msg.payload.team.id,\".svg\");\nnameIndex = msg.payload.team.name.lastIndexOf(\" \");\nmsg.payload.team.teamName = teams_info[msg.payload.team.id].teamName;\nmsg.payload.team.locationName = teams_info[msg.payload.team.id].locationName;\nmsg.payload.team.teamLink = teams_info[msg.payload.team.id].officialSiteUrl;\nfor (let [key, value] of Object.entries(msg.payload.team)) {\n  msg.payload[key] = value;\n}\ndelete msg.payload.team;\nfor (let [key, value] of Object.entries(msg.payload.leagueRecord)) {\n  msg.payload[key] = value;\n}\ndelete msg.payload.leagueRecord;\nfor (let [key, value] of Object.entries(msg.payload.streak)) {\n  msg.payload[key] = value;\n}\ndelete msg.payload.streak;\nmsg.payload.records.overallRecords.forEach(function(record){\n  msg.payload[record['type'].concat('Record')] = record['wins']+'-'+record['losses']\n  if ('ot' in record) { msg.payload[record['type'].concat('Record')] += ('-' + record['ot'])}\n})\ndelete msg.payload.records;\nlet pp = msg.payload.pointsPercentage.toFixed(3)\nmsg.payload.pointsPercentage = pp\nlet diff = msg.payload.goalsScored - msg.payload.goalsAgainst;\nmsg.payload.diff = ['','+'][Number(diff > 0)] + diff;\nlet dict = flow.get('teams') || {};\ndict[parseInt(msg.payload.divisionRank)-1] = msg.payload;\nflow.set('teams', dict);\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":1040,"y":460,"wires":[["dfeb420f.48dfe"]]},{"id":"9bb0c1d2.f2d92","type":"change","z":"57910e50.9be5","name":"Teams","rules":[{"t":"set","p":"teams","pt":"flow","to":"[]","tot":"json"},{"t":"set","p":"teamRecords","pt":"flow","to":"payload.teamRecords","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":550,"y":440,"wires":[["c3494727.b7ff58"]]},{"id":"c3494727.b7ff58","type":"array-loop","z":"57910e50.9be5","name":"Iterate Teams","key":"al61a1ecc6700c16","keyType":"msg","reset":true,"resetValue":"value-null","array":"teamRecords","arrayType":"flow","x":780,"y":440,"wires":[["63da734e.aae4bc"],["cb440b00.2b05b8"]]},{"id":"1b360c88.841663","type":"link in","z":"57910e50.9be5","name":"Continue Team Loop","links":["dfeb420f.48dfe"],"x":560,"y":380,"wires":[["c3494727.b7ff58"]]},{"id":"dfeb420f.48dfe","type":"link out","z":"57910e50.9be5","name":"Team Loop Out","links":["1b360c88.841663"],"x":1120,"y":460,"wires":[]},{"id":"63da734e.aae4bc","type":"link out","z":"57910e50.9be5","name":"Divisions Publish Out","links":["288b79.339fe488"],"x":915,"y":420,"wires":[]},{"id":"288b79.339fe488","type":"link in","z":"57910e50.9be5","name":"Division Publish","links":["63da734e.aae4bc"],"x":220,"y":640,"wires":[["4bd3c5b6.b603ec"]]},{"id":"aeed0d3.2d435f","type":"comment","z":"57910e50.9be5","name":"Publish DIvision Sensor","info":"","x":400,"y":540,"wires":[]},{"id":"83d08b12.a9db28","type":"comment","z":"57910e50.9be5","name":"NHL Teams","info":"","x":330,"y":130,"wires":[]},{"id":"1847dd23.db3cd3","type":"inject","z":"57910e50.9be5","name":"Get Hockey Teams","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"00 06 * * *","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":410,"y":180,"wires":[["dd0a488d.5d9c98"]]},{"id":"dd0a488d.5d9c98","type":"change","z":"57910e50.9be5","name":"Teams API","rules":[{"t":"set","p":"headers['User-Agent']","pt":"msg","to":"Chrome/68.0.3440.106 Safari/537.36","tot":"str"},{"t":"set","p":"url","pt":"msg","to":"https://statsapi.web.nhl.com/api/v1/teams","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":646,"y":180,"wires":[["8a11209f.2f9e2"]]},{"id":"8a11209f.2f9e2","type":"http request","z":"57910e50.9be5","name":"GET","method":"GET","ret":"obj","paytoqs":"ignore","url":"","tls":"","persist":false,"proxy":"","authType":"","x":820,"y":180,"wires":[["e310b957.021658"]]},{"id":"7c28cc56.eaf704","type":"array-loop","z":"57910e50.9be5","name":"Iterate Teams","key":"al61a1ecc6700c10","keyType":"msg","reset":false,"resetValue":"value-null","array":"team_array","arrayType":"flow","x":1249,"y":180,"wires":[[],["9038a4cc.722d58"]]},{"id":"9038a4cc.722d58","type":"function","z":"57910e50.9be5","name":"Put Team into array","func":"let dict = flow.get('nhl_teams') || {};\ndict[parseInt(msg.payload.id)] = msg.payload;\nflow.set('nhl_teams', dict);\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":1503,"y":179,"wires":[["418d1b5b.f87eb4"]]},{"id":"418d1b5b.f87eb4","type":"link out","z":"57910e50.9be5","name":"Team Array out","links":["9ef15b1.ab96ba8"],"x":1575,"y":180,"wires":[]},{"id":"9ef15b1.ab96ba8","type":"link in","z":"57910e50.9be5","name":"Team Array In","links":["418d1b5b.f87eb4"],"x":1046,"y":129,"wires":[["7c28cc56.eaf704"]]},{"id":"e310b957.021658","type":"change","z":"57910e50.9be5","name":"Set up flows","rules":[{"t":"set","p":"team_array","pt":"flow","to":"payload.teams","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":1049,"y":180,"wires":[["7c28cc56.eaf704"]]},{"id":"7a5303581d1d81c0","type":"debug","z":"57910e50.9be5","name":"Impossibru Division!","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","statusVal":"$flowContext('nhl_division_id')","statusType":"jsonata","x":1260,"y":400,"wires":[]},{"id":"28e7bd5c.77b7ca","type":"server","name":" Home Assistant","legacy":false,"addon":false,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]`



![image](https://user-images.githubusercontent.com/56559827/140669342-10298cb3-f2db-4224-adc6-3771c9ba6c4f.png)
![image](https://user-images.githubusercontent.com/56559827/140671863-21fcd92b-6c50-4006-850c-09c97127b7b3.png)

**Comment by nutsofamily** [comment]
I copied the raw and made a new node red. Sorry for lame question, how do I get the NHL sensors to show up. I currently am fowlling my teams without any issues but I seem to be missing the nhl sensor for the league stats.

**Comment by nutsofamily** [comment]
How do i get these to show up in my entities?
Are they required to be added to configuration.yaml manually?

If so do you have a raw yaml example.
Again....... Thanks SOO much



sensor.nhl_standings | Current League Standings
sensor.nhl_division_discover_central | Central Division standings
sensor.nhl_division_honda_west | West Division standings
sensor.nhl_division_scotia_north | North Division standings
sensor.nhl_division_mass_mutual_east | East Division standings

**Comment by nutsofamily** [comment]
I had to do do a major update on node-red and I see the sensors now but they dont provide any info.

**Comment by nutsofamily** [comment]
Must have needed an hour to update. It works now, just have to rename all these old weird divisions.
Sorry for all the replies.
